### ISSUE TITLE
Upgrade Spring Boot to the latest version

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-handling-form-submission#27]
Update the guide to use the most recent Spring Boot version.

To do so, change the Spring Boot version in:

initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml

**Comment by lavanyajain** [comment]
@Buzzardo Can you assign this to me for hacktober fest contribution

**Comment by lavanyajain** [comment]
@Buzzardo PR for this is here - https://github.com/spring-guides/gs-handling-form-submission/pull/28/files

**Comment by Buzzardo** [comment]
Thanks.
