### ISSUE TITLE
greetingSubmit method is quite confusing

### ISSUE THREAD

**Issue by buptfarmer** [spring-guides/gs-handling-form-submission#9]
In this project, the following code lead me to a great misunderstanding, I want to share it, and maybe I can help others. 
```   
// GreetingController.java
 @PostMapping("/greeting")
    public String greetingSubmit(@ModelAttribute Greeting greeting) {
        return "result";
    }

// result.html
<p th:text="'content: ' + ${greeting.content}"/>
```
At first glance in the result.html, I thought  `greeting` object may refer to the `@ModelAttribute Greeting greeting`,  then I tried to make some modification to use another model `OtherModel`, but it turned out to be exception.  
After google quite a while, I found out that here the `${greeting.content}` is linked to the name of the model class rather than the name of the key. 
So I believe that  the proper way to do this is like this.
```
    @PostMapping("/greeting2")
    public String greetingSubmit(@ModelAttribute OtherModel greeting, Model model) {
        model.addAttribute("greeting", greeting);
        return "result";
    }
```

Thanks

**Comment by gregturn** [comment]
In this guide, there are two parts being shown: the current value of the `Greeting` object as well as an HTML FORM used to submit updates to that object to the server.

The following line of code is where Thymeleaf is given a `greeting` object to operate on:

```
model.addAttribute("greeting", greeting);
```

To change from `Greeting` to `OtherModel`, you'd have to alter both controller methods. `"greeting"` is the handle applied to it for the template.

This bit of Thymeleaf is used to _show_ the current values of `Greeting` in the `result.html` template:
```
<h1>Result</h1>
<p th:text="'id: ' + ${greeting.id}" />
<p th:text="'content: ' + ${greeting.content}" />
<a href="/greeting">Submit another message</a>
```

In this case, the `Greeting` POJO fed into the template has both an `id` and a `content` attribute. (NOTE: Standard Java Bean rules apply).

When it comes time to build a form and POST it to the server, the same POJO is used to build an HTML FORM (`greeting.html`):

```
<form action="#" th:action="@{/greeting}" th:object="${greeting}" method="post">
    <p>Id: <input type="text" th:field="*{id}" /></p>
    <p>Message: <input type="text" th:field="*{content}" /></p>
    <p><input type="submit" value="Submit" /> <input type="reset" value="Reset" /></p>
</form>
```

* `th:object="${greeting}"` gets a hold of the `greeting` POJO.
* `th:field="*{id}"` references that bean's `id` field
* `th:field="*{content}"` references that bean's `content` field.

If you showed more details of your alteration, we might be able to debug further.
